export const CREATE_COMMENT = "COMMENT/CREATE_COMMENT";
export const DEL_COMMENT = "COMMENT/DEL_COMMENT";
export const DOWNLOAD_COMMENTS = "DOWNLOAD_COMMENTS";

export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";
export const SHOW_SPINNER = "APP/SHOW_SPINNER";
export const HIDE_SPINNER = "APP/HIDE_SPINNER";